eco1885/pairs_team-a

Gemfile
Gemfile.lock

#What
kaminari gemの導入
#Why
ページネーションの導入に必要なため

add gem 'kaminari'

---

Gemfile.lock
app/assets/stylesheets/application.scss
app/assets/stylesheets/modules/_sidecontents.scss
app/assets/stylesheets/pairs.scss
app/views/pairs/index.html.haml

トップview_fix

---

Gemfile
Gemfile.lock
config/unicorn.rb

#WHAT
unicorn導入
#WHY
本番環境導入により

unicorn_install

---

config/database.yml

#WHAT
database.ymlの本番環境ように編集
#WHY
必須機能により

database.yml_edit

---

config/unicorn.rb

unicorn.rb_fix

---

config/unicorn.rb

#WHAT
unicornファイルの作成
#WHY
必須機能により

unicorn_create

---

config/database.yml

databaseymlEdit

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/modules/_main_contents.scss
app/assets/stylesheets/modules/_main_footer.scss
app/assets/stylesheets/modules/_pagenation.scss
app/controllers/pairs_controller.rb
app/views/kaminari/_first_page.html.haml
app/views/kaminari/_gap.html.haml
app/views/kaminari/_last_page.html.haml
app/views/kaminari/_next_page.html.haml
app/views/kaminari/_page.html.haml
app/views/kaminari/_paginator.html.haml
app/views/kaminari/_prev_page.html.haml
app/views/pairs/index.html.haml
app/views/pairs/shared/_footer.html.haml
app/views/pairs/shared/_main_contents.html.haml
config/initializers/kaminari_config.rb

What
kaminariで導入したページネーションの装飾
使う頻度が高いフッターの部分テンプレート化
Why
必須機能ため

ページネーションのデザイン変更、footerの部分テンプレート化

---

app/views/layouts/application.html.haml
app/views/pairs/index.html.haml

What
Application.html.hamlに共通部分を追加
Why
記述を簡単にするため

layouts_edit

---

app/views/layouts/application.html.haml

Reverts eco1885/pairs_team-a#36

Revert "layouts_edit"

---

Gemfile

Reverts eco1885/pairs_team-a#39

Revert "GemfileEdit"

---

Capfile
Gemfile
Gemfile.lock
config/deploy.rb
config/deploy/production.rb
config/deploy/staging.rb
config/unicorn.rb

#WHAT
自動デプロイ機能の実装
#WHY
便利機能により

AutoDeploy

---

config/deploy.rb
config/unicorn.rb

AutoDeploy fix2

---

app/assets/stylesheets/mixin/_button_e.scss
app/assets/stylesheets/mixin/_button_gray_a.scss
app/assets/stylesheets/mixin/_button_orange_a.scss
app/assets/stylesheets/mixin/_button_pink_a.scss
app/assets/stylesheets/mixin/_button_pink_c.scss
app/assets/stylesheets/modules/_from_partner.scss
app/views/pairs/from_partner.html.haml

LIkeFromPartnerView

---

app/models/user_image.rb
db/migrate/20180322071513_create_user_images.rb
db/schema.rb
test/fixtures/user_images.yml
test/models/user_image_test.rb

What
ユーザーのimageテーブルの作成
Why
必須機能のため

ユーザーのimageテーブルの作成

---

app/assets/javascripts/showProfile.js
app/assets/stylesheets/modules/_search_one.scss
app/assets/stylesheets/pairs.scss
app/controllers/pairs_controller.rb
app/views/layouts/application.html.haml
app/views/pairs/search_one.html.haml
app/views/pairs/shared/_list_view_user_item.html.haml
app/views/pairs/shared/_main_contents.html.haml
app/views/pairs/shared/_search_one.html.haml

#what
プロフィールの詳細情報をjsを使い表示させた
#why
参考にしているサイトも同じことをしていたため

ProfileJsCreate

---

app/models/user.rb

#what
validation変更
#why
新規登録できなくなっているため

modifyvalidation

---

app/controllers/pairs_controller.rb
db/schema.rb

What
whereからfind_byに変更
why
touchメソッドを使用できなかったため

足跡機能whereからfind_byへ変更

---

app/assets/javascripts/search_form.js
app/assets/stylesheets/application.scss
app/assets/stylesheets/modules/search_form.scss
app/controllers/details_controller.rb
app/controllers/searches_controller.rb
app/views/pairs/search.html.haml
app/views/pairs/search_start.html.haml
app/views/pairs/shared/_list_view_user_item.html.haml
app/views/searches/search_index.html.haml
config/routes.rb
db/schema.rb

pullrequest#77#78commit

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/modules/search_index.scss

確認3cssコミット

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/mixin/_allow_icon.scss
app/assets/stylesheets/modules/details-edit.scss
app/assets/stylesheets/modules/registration.scss
app/assets/stylesheets/modules/search_index.scss
app/controllers/searches_controller.rb
app/views/details/edit.html.haml
app/views/devise/registrations/new.html.haml
app/views/pairs/shared/_list_view_user_item.html.haml

#what
ユーザー詳細情報入力画面の編集
#why
検索に必要なため

Add css to user edit view branch

---

app/assets/stylesheets/modules/details-edit.scss
app/assets/stylesheets/modules/search_index.scss
app/controllers/details_controller.rb
app/controllers/searches_controller.rb
app/models/smoke.rb
app/models/user.rb
app/views/details/edit.html.haml
app/views/searches/search_index.html.haml
db/migrate/20180329102844_create_smokes.rb
db/migrate/20180329103104_add_smoke_to_users.rb
db/schema.rb
test/fixtures/smokes.yml
test/models/smoke_test.rb

add smoke-model

---

app/controllers/searches_controller.rb

What
検索結果が出ない不具合の修正
Why
エラーのため

検索結果が出ない不具合の修正

---

app/assets/javascripts/displayNumber.js
app/controllers/searches_controller.rb
app/views/pairs/shared/_box_search_menu.html.haml
app/views/pairs/shared/_main_contents.html.haml
app/views/searches/search_result.html.haml

What
検索結果を表示する際のエラーの修正
Why
エラーの修正のため

検索結果を表示する際のエラーの修正

---

db/migrate/20180322071513_create_user_images.rb
db/schema.rb

foreign_keyの記述の修正

---

app/assets/stylesheets/modules/_main_contents.scss
db/schema.rb

表示人数のview崩れの変更

---

app/assets/javascripts/parts.js
app/views/communities/show.html.haml

#what
コミュニティ入会・退会ボタンの表示について、条件によって変わる機能
#why
コミュニティ機能の必須条件

コミュニティ入会・退会ボタンの表示を条件によって変わるように修正

---

app/views/messages/shared/_match_user.html.haml
app/views/messages/shared/_their_message.html.haml
db/schema.rb

message画面のviewの変更
